import { ExpansionPanelDetails } from "@material-ui/core";
import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "Joe",
      email: "tinotendajoe01@gmail.com",
      password: bcrypt.hashSync("tinotendA01!"),
      isAdmin: true,
    },
    {
      name: "Jane",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Uraige",
      slug: "uriage",
      category: "Personal Care",
      image: "/products/demo (1).png",
      price: 13,
      brand: "HYSEAC",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Cleansing Gel",
    },
    {
      name: "Gingembre",
      slug: "gingembre",
      category: "Cosmetics",
      image: "/products/cosmetics/cosmetics (9).png",
      price: 33,
      isFeatured: true,
      brand: "Roger & Gallet",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Cleansing Gel",
    },
    {
      name: "Hyseac",
      slug: "Hyseac",
      category: "Personal Care",
      image: "/products/demo (2).png",
      price: 15,
      brand: "Hyseac",
      rating: 5,
      numReviews: 10,
      countInStock: 20,
      description: "Extra rich dermatological",
    },
    {
      name: "Murine",
      slug: "murine",
      category: "Eye Care",
      image: "/products/eyes/eyes (11).png",
      price: 13,
      brand: "Murine",
      isFeatured: true,
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Bright & Moist Eye Drops",
    },
    {
      name: "Furterer ",
      slug: "furterer",
      category: "Skin Care",
      image: "/products/demo (4).png",
      isFeatured: true,
      price: 20,
      brand: "Okara",
      rating: 3.5,
      numReviews: 10,
      countInStock: 30,
      description: "Color protection mask",
    },
    {
      name: "Optive Fusion",
      slug: "optivefusion",
      category: "Eye Care",
      image: "/products/eyes/eyes (3).png",
      price: 13,
      brand: "Allergran",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description:
        "For relief, comfort and sustained protection from dry eye symptoms",
    },
    {
      name: "Vichy ",
      slug: "vichy",
      category: "Hair Care",
      image: "/products/demo (1).png",
      price: 13,
      brand: "Decos",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Shampooing Doux Fortifiant",
    },
    {
      name: "5 Sense",
      slug: "5sense",
      category: "Cosmetics",
      image: "/products/cosmetics/cosmetics (1).png",
      price: "45",
      brand: "FURTERER",
      isFeatured: true,
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Enhanncing dry oil",
    },
    //gifts
    {
      name: "Mary Kay gifts for Him",
      slug: "tribute",
      category: "For Him",
      image: "/products/gifts/g (1).jpg",
      price: 13,
      brand: "tribute",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Mary Kay gifts for Him. The Graduate & Dad.",
      isGift: true,
    },
    {
      name: "Skin care Set for Him",
      slug: "tribute1",
      category: "For Him",
      image: "/products/gifts/g (2).jpg",
      price: 13,
      brand: "Nivea",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Gift For Him | GiftallBD",
      isGift: true,
    },
    {
      name: "Fogg Scent",
      slug: "tribute2",
      category: "For Him",
      image: "/products/gifts/g (3).jpg",
      price: 13,
      brand: "Trump",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Gift For Him | GiftallBD",
      isGift: true,
    },
    {
      name: "Fogg Scent",
      slug: "tribut41",
      category: "For Him",
      image: "/products/gifts/g (3).jpg",
      price: 13,
      brand: "wilton",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Gift For Her | GiftallBD",
      isGift: true,
    },
    {
      name: "Beauty Gifts",
      slug: "tribute1sss",
      category: "For Him & Her",
      image: "/products/gifts/g (5).jpg",
      price: 13,
      brand: "Beauty",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Best Valentine's Beauty Gifts for him and her!",
      isGift: true,
    },
    {
      name: "Blissful",
      slug: "tribute13ss",
      category: "For Her",
      image: "/products/gifts/g (8).jpg",
      price: 13,
      brand: "Lush",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Lush Cosmetics",
      isGift: true,
    },
    {
      name: "For Him & Her",
      slug: "tributedd4d1",
      category: "For Him & Her",
      image: "/products/gifts/g (9).jpg",
      price: 13,
      brand: "__",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Best Beauty Gifts for him and her!",
      isGift: true,
    },
    {
      name: "Home Spa",
      slug: "tributeddd1",
      category: "For Her",
      image: "/products/gifts/g (10).jpg",
      price: 13,
      brand: "Lovely",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Gift Baskets for women, home spa set for her",
      isGift: true,
    },
  ],

  cats: [
    { name: "Pills", image: "/products/categories/pills.svg" },
    { name: "Rx", image: "/products/categories/prescription.svg" },
    { name: "Rx", image: "/products/categories/prescription-bottle.svg" },
    { name: "Baby", image: "/products/categories/baby.svg" },
  ],
  options: [
    {
      name: "Drug Info",
      image: "/products/account/info.svg",
      url: "drug-info",
    },
    {
      name: "Scheduler",
      image: "/products/account/calendar.png",
      url: "support",
    },
    {
      name: "Store",
      image: "/products/account/logo-shopify.svg",
      url: "shop",
    },
    {
      name: "Pocket",
      image: "/products/account/money-check-alt.png",
      url: "pocket",
    },

    {
      name: "My Meds",
      image: "/products/account/prescription-bottle.png",
      url: "prescription/history",
    },
    {
      name: "Locate",
      image: "/products/account/location-arrow.png",
      url: "locate",
    },
  ],
  drugs: [
    {
      name: "Ampicillin",
      genericName: "Aminobenzylpenicillin",
      image: "/drugs/d (1).png",
      standardDose: "2000 mg",
      adultDose: "2000 mg",
      kidsDose: "**g",
      minDuration: 1,
      maxDuration: 14,
      slug: "Ampicillin",
      category: "Antibiotics",
      price: 5,
      isAvailable: true,
      adverseEffects:
        "Skin rashes,diarrhoea and nausea and vomiting, occur quite often, usually after oral use.Ampicillin should be stopped if a skin rash occurs. It should preferably not be given to patients with infectious mononucleosis since they are especially susceptible to ampicillin-induced skin rashes; patients with lymphatic leukaemia or possibly HIV infection may also be at increased risk of developing skin rashes.",
      description:
        "Inhibits bacterial growth by interfering with the transpeptidation reaction of bacterial cell wall synthesis",
    },
    {
      name: "Gentamicin",
      genericName: "Gentamicin",
      image: "/drugs/d (2).png",
      standardDose: "4–5 mg/kg",
      adultDose: "4–5 mg/kg",
      kidsDose: "**mg/kg",
      minDuration: 1,
      maxDuration: 14,
      slug: "Gentamicin",
      category: "Antibiotics",
      price: 5,
      isAvailable: true,
      adverseEffects:
        "Ototoxicity,ephrotoxicity, respiratory depression and muscular paralysis",
      description:
        "Inhibits bacterial growth by e, inhibiting protein synthesis and generating errors in the transcription of the genetic code. The manner in which cell death is brought about is imperfectly understood, and other mechanisms may contribute, including effects on membrane permeability. ",
    },

    {
      name: "Losartan",
      genericName: "Gentamicin",
      image: "/drugs/d (2).png",
      standardDose: "25-100mg",
      adultDose: "25-100mg",
      kidsDose: "**mg",
      minDuration: 1,
      maxDuration: 30,
      slug: "Losartann",
      category: "Antihypertension",
      price: 5,
      isAvailable: true,
      adverseEffects:
        "Ototoxicity,ephrotoxicity, respiratory depression and muscular paralysis",
      description:
        "Inhibits bacterial growth by e, inhibiting protein synthesis and generating errors in the transcription of the genetic code. The manner in which cell death is brought about is imperfectly understood, and other mechanisms may contribute, including effects on membrane permeability. ",
    },
  ],
};
export default data;
